- name: AdamW
  params:
  kwargs:
    lr: 0.0001              # 0.1 × batch/128
    weight_decay: 0.0001
  scheduler_on_step:   # on gère tout dans SequentialLR
    name: OneCycleLR
    kwargs:
      max_lr: 0.001
      pct_start: 0.3
      div_factor: 10
      final_div_factor: 100
      epochs: 100
      steps_per_epoch: 75
  scheduler_on_epoch:
  scheduler_on_val: