name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: convnext
  bb_name: convnext_tiny   # Vous pouvez changer pour 'convnext_tiny' ou 'convnext_base'
  embed_dim: 384
  frozen: false             # false = Fine-Tuning complet du réseau
  without_fc: false         # On veut la couche de projection
  with_autocast: true       # Compatible avec votre mixed precision !
  pretrained: true          # Utiliser les poids pré-entraînés sur ImageNet