# @package _group_
name: MultiDinoHashing
freeze_batch_norm: false
freeze_pos_embedding: false
kwargs:
  # Liste de vos 4 branches (Ondelettes : LL, LH, HL, HH)
  backbones_config:
    - name: 'dinov2_vits14'
      frozen: true  # On gèle DINO pour laisser l'attention apprendre en premier
    - name: 'dinov2_vits14'
      frozen: true
    - name: 'dinov2_vits14'
      frozen: true
    - name: 'dinov2_vits14'
      frozen: true

  # Configuration du Hachage
  binary_config:
    nbits: 64  # Doit être identique à la Baseline pour comparer équitablement !
    
  # Configuration du Goulot d'Étranglement (SOTA)
  fusion_config:
    type: 'cross_attention_bottleneck' # Active notre nouvelle classe
    output_dim: 384                    # Dimension latente
    num_heads: 8                       # Multi-têtes pour des relations complexes
    dropout: 0.1
    # -- Nouveaux paramètres SOTA (Hybrid Regularization) --
    num_queries: 4                     # 4 experts pour séparer les 4 bandes
    sub_band_dropout_p: 0.3            # Force le réseau à explorer LH, HL, HH
    ortho_weight: 0.1                  # Force la division du travail (sans exploser la loss)

  with_autocast: true