# @package _group_
name: RetrievalNet
freeze_batch_norm: False
freeze_pos_embedding: False
kwargs:
  backbone_name: resnet_hashing_2
  embed_dim: 2048
  norm_features: False
  without_fc: True
  with_autocast: False
  pretrained: True
  n_bits: 64
  tanh : True
