# @package _group_
train:
  Resize:
    size: [256, 256]
  RandomCrop:
    size: [224, 224]
  RandomHorizontalFlip:
    p: 0.5
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

test:
  Resize:
    size: [256, 256]
  CenterCrop:
    size: [224, 224]
  ToTensor: {}
  Normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]